CREATE OR REPLACE
ALGORITHM = UNDEFINED VIEW `view_rcycle_epcs_events_properties` (
`epc_id_raw`,
`event_id`,
`epc_join_key`,
`gtin`,
`lot_number`,
`product_name`,
`brand`,
`primary_image`,
`event_time`,
`biz_location_join_key`,
`read_point_join_key`,
`product_join_key`,
`production_step`,
`quantity`,
`quantity_uom`,
`detailed_name`,
`content_of_packaging`,
`packaging_type`,
`packaging_level`,
`object_form`,
`product_producer`,
`producer_address`,
`product_brand`,
`internal_batch`,
`article_number`,
`product_shape`,
`product_type`,
`product_class`,
`application_range`,
`outside_surface_stype`,
`inside_surface_stype`,
`sealing_cond_min`,
`sealing_cond_min_uom`,
`sealing_cond_max`,
`sealing_cond_max_uom`,
`form_temp_min`,
`form_temp_min_uom`,
`form_temp_max`,
`form_temp_max_uom`,
`treatment_type`,
`treated_side`,
`print_type`,
`unit_weight`,
`unit_weight_uom`,
`substrate_width`,
`substrate_width_uom`,
`winding_core_type`,
`winding_core`,
`winding_core_uom`,
`winding_tension_start`,
`winding_tension_start_uom`,
`winding_tension_end`,
`winding_tension_end_uom`,
`reel_weight`,
`reel_weight_uom`,
`reel_diameter`,
`reel_diameter_uom`,
`unit_length`,
`unit_length_uom`,
`unit_width`,
`unit_width_uom`,
`unit_height`,
`unit_height_uom`,
`filling_volume`,
`filling_volume_uom`,
`packaging_unit`,
`packaging_unit_number`,
`mfr`,
`mfr_uom`
) AS
SELECT
    `e`.`epc_id_raw` AS `epc_id_raw`,
    `e`.`event_id` AS `event_id`,
    `e`.`epc_join_key` AS `epc_join_key`,
    `p`.`gtin` AS `gtin`,
    `e`.`lot_number` AS `lot_number`,
    `p`.`product_name` AS `product_name`,
    `p`.`brand` AS `brand`,
    `p`.`primary_image` AS `primary_image`,
    `e`.`event_time` AS `event_time`,
    `e`.`biz_location_join_key` AS `biz_location_join_key`,
    `e`.`read_point_join_key` AS `read_point_join_key`,
    `e`.`product_join_key` AS `product_join_key`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:productionStep"')) AS `production_step`,
    `e`.`quantity` AS `quantity`,
    `e`.`uom` AS `quantity_uom`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:detailedName"')) AS `detailed_name`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."example:contentOfPackaging"')) AS `content_of_packaging`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."gs1:packagingType"')) AS `packaging_type`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:packagingLevel"')) AS `packaging_level`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:objectForm"')) AS `object_Form`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:productProducer"')) AS `product_producer`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:producerAddress"')) AS `producer_address`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:productBrand"')) AS `product_brand`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:internalBatch"')) AS `internal_batch`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:articleNumber"')) AS `article_number`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:productShape"')) AS `product_shape`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:productType"')) AS `product_type`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:productClass"')) AS `product_class`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."example:applicationRange"')) AS `application_range`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:outsideSurfaceType"')) AS `outside_surface_stype`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:insideSurfaceType"')) AS `inside_surface_stype`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:sealingCondMin"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `sealing_cond_min`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:sealingCondMin"."rcycle:unitCode"')) AS `sealing_cond_min_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:sealingCondMax"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `sealing_cond_max`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:sealingCondMax"."rcycle:unitCode"')) AS `sealing_cond_max_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:formTempMin"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `form_temp_min`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:formTempMin"."rcycle:unitCode"')) AS `form_temp_min_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:formTempMax"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `form_temp_max`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:formTempMax"."rcycle:unitCode"')) AS `form_temp_max_uom`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:treatmentType"')) AS `treatment_type`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:treatedSide"')) AS `treated_side`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:printType"')) AS `print_type`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."example:unitWeight"."example:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `unit_weight`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."example:unitWeight"."example:unitCode"')) AS `unit_weight_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:substrateWidth"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `substrate_width`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:substrateWidth"."rcycle:unitCode"')) AS `substrate_width_uom`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:windingCoreType"')) AS `winding_core_type`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:windingCore"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `winding_core`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:windingCore"."rcycle:unitCode"')) AS `winding_core_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:windingTensionStart"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `winding_tension_start`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:windingTensionStart"."rcycle:unitCode"')) AS `winding_tension_start_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:windingTensionEnd"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `winding_tension_end`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:windingTensionEnd"."rcycle:unitCode"')) AS `winding_tension_end_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:reelWeight"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `reel_weight`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:reelWeight"."rcycle:unitCode"')) AS `reel_weight_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:reelDiameter"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `reel_diameter`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:reelDiameter"."rcycle:unitCode"')) AS `reel_diameter_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:unitLength"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `unit_length`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:unitLength"."rcycle:unitCode"')) AS `unit_length_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:unitWidth"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `unit_width`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:unitWidth"."rcycle:unitCode"')) AS `unit_width_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:unitHeight"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `unit_height`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:unitHeight"."rcycle:unitCode"')) AS `unit_height_uom`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:fillingVolume"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `filling_volume`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:fillingVolume"."rcycle:unitCode"')) AS `filling_volume_uom`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:packagingUnit"')) AS `packaging_unit`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:packagingUnitNumber"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `packaging_unit_number`,
    CAST(NULLIF(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:mfr"."rcycle:value"'), _UTF8MB4'null') AS DECIMAL(10, 2)) AS `mfr`,
    JSON_UNQUOTE(JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:mfr"."rcycle:unitCode"')) AS `mfr_uom`
FROM
    ((`data`.`epc_events` AS `e`
LEFT JOIN `data`.`epcis_events_raw` AS `er` ON
    `e`.`event_id` = `er`.`event_id`)
LEFT JOIN `data`.`product` AS `p` ON
    `p`.`id` = `e`.`product_join_key`)
WHERE
    `e`.`epc_rel_type` NOT IN (_UTF8MB4'inputQuantityList') AND
    JSON_EXTRACT(`er`.`event_body`, _UTF8MB4'$.ilmd."rcycle:productionStep"') IS NOT NULL
